name: Linting

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches-ignore:
      - main

jobs:
  eslint-score:
    runs-on: ubuntu-latest
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '16.x'
      
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Install ESLint
        run: npm install eslint
      
      - name: Setup ESLint Score
        uses: suryaumapathy2812/ESlint-score@v1
        with:
          action: "SETUP"
          start-point: './'

      - name: run ESlint
        run: npx eslint -c ./.eslintrc.custom.json --ext .js --output-file eslint-results.json --format json ./ || true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint-results.json"

      - name: Run ESLint Score
        uses: suryaumapathy2812/ESlint-score@v1
        with:
          action: "SCORE"
          start-point: './'
      
      - name: Display ESLint Score
        run: |
          echo "ESLint Score: ${{ steps.eslint-score.outputs.score }}"
