on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches-ignore:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Topic Tagging
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Topic Tagger
        id: topic-tagger
        uses: suryaumapathy2812/topic-tagger-action@v1
        with:
          start-point: "./"
          version: "v4"
          github_token: ${{ secrets.GITHUB_TOKEN }}